feat: registry agnostic + input validation

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -8,7 +8,7 @@ inputs:
     required: false
   IMAGE_NAME:
     required: true
-  GCR_JSON_KEY:
+  REGISTRY_JSON_KEY:
     required: true
   SECURITY_SCAN:
     type: boolean
@@ -17,6 +17,15 @@ inputs:
 runs:
   using: "composite"
   steps:
+  - name: Check inputs
+    shell: bash
+    run: |
+      if [ -z "${{inputs.IMAGE_REPOSITORY}}" ]; then echo "inputs.IMAGE_REPOSITORY is missing"; exit=1; fi
+      if [ -z "${{inputs.BUILD_CONTEXT}}" ]; then echo "inputs.BUILD_CONTEXT is missing"; exit=1; fi
+      if [ -z "${{inputs.IMAGE_NAME}}" ]; then echo "inputs.IMAGE_NAME is missing"; exit=1; fi
+      if [ -z "${{inputs.REGISTRY_JSON_KEY}}" ]; then echo "inputs.REGISTRY_JSON_KEY is missing"; exit=1; fi
+      if [ -z "$exit" ]; then exit 1; fi
+
   - name: Checkout code
     uses: actions/checkout@v2
     
@@ -36,12 +45,12 @@ runs:
     id: buildx
     uses: docker/setup-buildx-action@v1
 
-  - name: Login to GCR
+  - name: Login to registry
     uses: docker/login-action@v1
     with:
-      registry: europe-west1-docker.pkg.dev
+      registry: ${{ inputs.IMAGE_REPOSITORY }}
       username: _json_key
-      password: ${{ inputs.GCR_JSON_KEY }}
+      password: ${{ inputs.REGISTRY_JSON_KEY }}
     
   - name: Build image localy first
     uses: docker/build-push-action@v2
@@ -71,7 +80,7 @@ runs:
       severity: 'CRITICAL,HIGH'
       trivyignores: .trivyignore
 
-  - name: Build image and push to Docker Hub and GitHub Container Registry
+  - name: Build image and push to registry
     uses: docker/build-push-action@v2
     id: docker_build_push
     with:
